### ISSUE TITLE
Post to gracedb with json for machine parsing

### ISSUE THREAD

**Issue by duncanmmacleod** [reedessick/OmegaScan_scheduler#2]
It would be good to have a `.json` packet uploaded to gracedb, rather than/as well as the current text message with a link. This is required to be able to parse the `png` image representing the h(t) scan for `<img>` linking into low-latency DQ reports.

In order to directly link the _h(t)_ image, we required one of
- the exact GPS time of the scan (string as passed to `wpipeline`)
- the URL of the png

Either one of those included in the JSON would be great.

**Comment by reedessick** [comment]
resolved by commit b87c5f0969ce72e7205eb025aa4dcf00c2dca8f0
